# Generated by Django 6.0.6 on 2026-06-24 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_negotiationlog_alter_transactionauditlog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=255)),
                ('target_agent_id', models.CharField(max_length=255)),
                ('requesting_buyer_id', models.CharField(blank=True, default='', max_length=255)),
                ('trust_score', models.IntegerField(default=0)),
                ('result_json', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transactionauditlog',
            name='is_disputed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
